import {
  LayoutDashboard,
  Users,
  Activity,
  FileBadge,
  School,
  ListChecks,
  ClipboardCheck,
  UserCog,
  Shield,
} from 'lucide-react';

export const MenuItems = [
  {
    title: 'Dashboard',
    icon: LayoutDashboard,
    url: '/dashboard',
    module: 'dashboard',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Trainer', 'Candidate'],
  },
  {
    title: 'System Users',
    icon: UserCog,
    url: '/users',
    module: 'users',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
  },
  {
    title: 'Institutes',
    icon: School,
    url: '/institutes',
    module: 'institutes',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
  },
  {
    title: 'Cadet Management',
    icon: Users,
    url: '/cadets',
    module: 'cadets',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Trainer'],
  },
  {
    title: 'Screening',
    icon: ClipboardCheck,
    url: '/screening',
    module: 'screening',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Trainer'],
  },
  {
    title: 'Tests & Interviews',
    icon: ListChecks,
    url: '/tests',
    module: 'tests',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Trainer'],
  },
  {
    title: 'Medical & Docs',
    icon: FileBadge,
    url: '/medical',
    module: 'medical',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Trainer'],
  },
    {
    title: 'Role Permissions',
    icon: Shield,
    url: '/role-permissions',
    module: 'role-permissions',
    action: 'manage',
    allowedRoles: ['SuperAdmin'],
  },
  {
    title: 'Activity Logs',
    icon: Activity,
    url: '/activity-logs',
    module: 'activity-logs',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
  },

];
