import {
  LayoutDashboard,
  Users,
  Activity,
  FileBadge,
  School,
  ListChecks,
  ClipboardCheck,
  UserCog,
  Shield,
  FileText,
  Stethoscope,
} from 'lucide-react';

export const MenuItems = [
  {
    title: 'Dashboard',
    icon: LayoutDashboard,
    url: '/dashboard',
    module: 'dashboard',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Institute', 'Cadet'],
  },
  {
    title: 'System Users',
    icon: UserCog,
    url: '/users',
    module: 'users',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
  },
  {
    title: 'Vessel Master',
    icon: School, // Will find a better icon if needed later, using School temporarily as Ship is not imported
    url: '/vessels',
    module: 'vessel-master',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
  },
  {
    title: 'Medical Centers',
    icon: Stethoscope,
    url: '/medical-centers',
    module: 'medical-centers',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
  },
  {
    title: 'Institutes',
    icon: School,
    module: 'institutes',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
    subItems: [
      {
        title: 'All Institutes',
        icon: School,
        url: '/institutes',
        module: 'institutes',
        action: 'view',
        exact: true,
      },
      {
        title: 'Submissions',
        icon: FileText,
        url: '/institutes/submissions',
        module: 'institutes',
        action: 'view',
      },
    ],
  },
  {
    title: 'Cadet Management',
    icon: Users,
    module: 'cadets',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Institute'],
    subItems: [
      {
        title: 'Engine Cadets',
        icon: Users,
        url: '/cadets/engine',
        module: 'cadets',
        action: 'view',
      },
      {
        title: 'Deck Cadets',
        icon: Users,
        url: '/cadets/deck',
        module: 'cadets',
        action: 'view',
      },
      {
        title: 'Shortlisted Cadets',
        icon: ListChecks,
        url: '/cadets/shortlist',
        module: 'cadets',
        action: 'view',
      },
    ],
  },
  {
    title: 'Submit Excel',
    icon: FileText,
    url: '/institute/submit-excel',
    module: 'submit-excel',
    action: 'view',
    allowedRoles: ['Institute'],
  },
  {
    title: 'Shortlisted Cadets',
    icon: ListChecks,
    url: '/institute/shortlisted-cadets',
    module: 'shortlisted-cadets',
    action: 'view',
    allowedRoles: ['Institute'],
  },
  {
    title: 'Screening',
    icon: ClipboardCheck,
    url: '/screening',
    module: 'screening',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Institute'],
  },
  {
    title: 'Tests & Interviews',
    icon: ListChecks,
    url: '/assessments',
    module: 'tests',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Institute'],
  },
  {
    title: 'Medical & Docs',
    icon: FileBadge,
    url: '/medical',
    module: 'medical',
    action: 'view',
    allowedRoles: ['SuperAdmin', 'Institute'],
  },
  {
    title: 'Role Permissions',
    icon: Shield,
    url: '/role-permissions',
    module: 'role-permissions',
    action: 'manage',
    allowedRoles: ['SuperAdmin'],
  },
  {
    title: 'Activity Logs',
    icon: Activity,
    url: '/activity-logs',
    module: 'activity-logs',
    action: 'view',
    allowedRoles: ['SuperAdmin'],
  },
];
